local deftest = require("deftest.deftest")

function init(self)
	deftest.add(require("test.test_token"))
	deftest.add(require("test.test_tokens"))
	deftest.add(require("test.test_containers"))
	deftest.add(require("test.test_load_json"))
	deftest.add(require("test.test_token_logger"))

	local is_report = (sys.get_config("test.report") == "1")
	deftest.run({ coverage = { enabled = is_report } })
end
