local deftest = require("deftest.deftest")

function init(self)
	deftest.add(require("test.test_token"))
	deftest.add(require("test.test_token_infinity"))
	deftest.add(require("test.test_token_visual"))
	deftest.add(require("test.test_token_restore"))
	deftest.add(require("test.test_token_events"))
	deftest.add(require("test.test_token_state"))
	deftest.add(require("test.test_token_groups"))
	deftest.add(require("test.test_containers"))
	deftest.add(require("test.test_load_json"))
	deftest.add(require("test.test_token_logger"))
	deftest.add(require("test.test_token_config"))

	local is_report = (sys.get_config_int("test.report") == 1)
	deftest.run({ coverage = { enabled = is_report } })
end
